import { lazy } from 'react';

export const HomePage = lazy(() => import('../pages/HomePage'));
export const CategoryPage = lazy(() => import('../pages/CategoryPage'));
export const LoginPage = lazy(() => import('../pages/LoginPage'));
export const SearchPage = lazy(() => import('../pages/SearchPage'));
export const DetailPage = lazy(() => import('../pages/DetailPage'));
export const ProductReviewsPage = lazy(() => import('../pages/ProductReviewsPage'));
export const ProductQaPage = lazy(() => import('../pages/ProductQaPage'));
export const ShopPage = lazy(() => import('../pages/ShopPage'));
export const FeaturedShopsPage = lazy(() => import('../pages/FeaturedShopsPage'));
export const CartPage = lazy(() => import('../pages/CartPage'));
export const CreateOrderPage = lazy(() => import('../pages/CreateOrderPage'));
export const CheckoutPage = lazy(() => import('../pages/CheckoutPage'));
export const PayPage = lazy(() => import('../pages/PayPage'));
export const OrderListPage = lazy(() => import('../pages/OrderListPage'));
export const OrderDetailPage = lazy(() => import('../pages/OrderDetailPage'));
export const OrderReviewPage = lazy(() => import('../pages/OrderReviewPage'));
export const OrderReturnPage = lazy(() => import('../pages/OrderReturnPage'));
export const ProfilePage = lazy(() => import('../pages/ProfilePage'));
export const FavoritesPage = lazy(() => import('../pages/FavoritesPage'));
export const MessagesPage = lazy(() => import('../pages/MessagesPage'));
export const ChatPage = lazy(() => import('../pages/ChatPage'));
export const FootprintsPage = lazy(() => import('../pages/FootprintsPage'));
export const AddressPage = lazy(() => import('../pages/AddressPage'));
export const ActivityPage = lazy(() => import('../pages/ActivityPage'));
