import RequireUserAuth from '../components/h5/RequireUserAuth';
import {
  ActivityPage,
  AddressPage,
  CartPage,
  CategoryPage,
  ChatPage,
  CheckoutPage,
  CreateOrderPage,
  DetailPage,
  FavoritesPage,
  ProductReviewsPage,
  ProductQaPage,
  FeaturedShopsPage,
  FootprintsPage,
  HomePage,
  LoginPage,
  MessagesPage,
  OrderDetailPage,
  OrderListPage,
  OrderReviewPage,
  OrderReturnPage,
  PayPage,
  ProfilePage,
  SearchPage,
  ShopPage,
} from './h5LazyPages';

/** H5 商城前台路由（不含 Admin），页面懒加载 */
export const h5Routes = [
  { index: true, Component: HomePage },
  { path: 'home', Component: HomePage },
  { path: 'category', Component: CategoryPage },
  { path: 'search', Component: SearchPage },
  { path: 'login', Component: LoginPage },
  { path: 'activity/:slug', Component: ActivityPage },
  { path: 'detail/:goodId', Component: DetailPage },
  { path: 'detail/:goodId/reviews', Component: ProductReviewsPage },
  { path: 'detail/:goodId/qa', Component: ProductQaPage },
  { path: 'featured-shops', Component: FeaturedShopsPage },
  { path: 'shop/:shopId', Component: ShopPage },
  {
    element: <RequireUserAuth />,
    children: [
      { path: 'cart', Component: CartPage },
      { path: 'createOrder/:goodId', Component: CreateOrderPage },
      { path: 'checkout', Component: CheckoutPage },
      { path: 'pay/:orderId', Component: PayPage },
      { path: 'orderList', Component: OrderListPage },
      { path: 'orderDetail/:orderId', Component: OrderDetailPage },
      { path: 'orderReview/:orderId', Component: OrderReviewPage },
      { path: 'orderReturn/:orderId', Component: OrderReturnPage },
      { path: 'profile', Component: ProfilePage },
      { path: 'messages', Component: MessagesPage },
      { path: 'messages/chat/:messageId', Component: ChatPage },
      { path: 'favorites', Component: FavoritesPage },
      { path: 'footprints', Component: FootprintsPage },
      { path: 'address', Component: AddressPage },
    ],
  },
];

export const h5RoutePaths = {
  home: '/home',
  category: '/category',
  search: '/search',
  featuredShops: '/featured-shops',
  cart: '/cart',
  profile: '/profile',
  login: '/login',
  orderList: '/orderList',
  messages: '/messages',
  favorites: '/favorites',
  footprints: '/footprints',
  address: '/address',
};
